name: Bug Report
description: 🐛 File a bug report
title: "[🐛 BUG]: "
labels: ["bug"]
assignees:
  - butschster
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How to reproduce the issue?
      description: Steps on how to reproduce the issue?

  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: 1.0.0
      value: "0.4.0"
