blank_issues_enabled: false

contact_links:
  - name: ❓ Start a discussion or ask a question on our Discord server.
    url: https://discord.gg/8bZsjYhVVk
    about: Please ask and answer questions here.
